/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_information;

import javax.swing.BorderFactory;
import java.awt.Color;
import javax.swing.border.Border;
import javax.swing.*;
import java.awt.event.*;
import java.awt.FlowLayout;
import static java.time.Clock.system;
import javax.swing.JTextField;

/**
 *
 * @author bigya
 */
public class Sign_Up_Form extends javax.swing.JFrame {

    /**
     * Creates new form Sign_Up_Form
     */
    public Sign_Up_Form() {
        initComponents();
        
        
         // center the form
        this.setLocationRelativeTo(null);
        
        // creating a border for jlable 1 and jlable 2
         Border mini_label1_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
         mini_label1.setBorder(mini_label1_border);
        
         Border cancel_label2_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
         cancel_lable2.setBorder(cancel_label2_border);
        
        // create border for the text and password fields
        Border field_border = BorderFactory.createMatteBorder(1 ,1 ,1 ,1,Color.black);
        first_name_field.setBorder(field_border);
        last_name_field.setBorder(field_border);
        email_field.setBorder(field_border);
        password_field.setBorder(field_border);
        conform_password_field.setBorder(field_border);
        phone_number_field.setBorder(field_border);
        
        // creating a button group for the radio buttons, helps select one from the list
        ButtonGroup group = new ButtonGroup();
        group.add(male_radio_button);
        group.add(female_radio_button);
    }
    // creating functions to identify the empty fields
    public boolean verifyFields()
    {
       // String fstName = first_name_field.getText();
       // String lastName = last_name_field.getText();
        //String email = email_field.getText();
        //String password = String.valueOf(password_field.getPassword());
       // String confPassword = String.valueOf(conform_password_field.getPassword());
        
        if(first_name_field.getText().equals("") || last_name_field.getText().equals("") ||
              email_field.getText().equals("") ||  (password_field.getPassword().equals("") ) ||
              (conform_password_field.getPassword().equals(""))  )
        {
            JOptionPane.showMessageDialog(null, "one or More Fields Are Empty");
            return false;
        }
        
        //checking two passwords are same
        else if(password_field.getPassword().equals(conform_password_field.getPassword()))
                {
                    JOptionPane.showMessageDialog(null, "The Password does not Match! Try Again");
                    return false;
                }
        
        else
        {
            return true;
        }
        
    }
    
    // creating a FUNCTION TO CHECK IF THE ENTERED USERNAME ALREADY EXISTS IN DATABASE

   // public boolean checkusrname(String usrname)
  //  {
        //PreparedStatement st;
        
   // }
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        signup_field = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        firstname_label = new javax.swing.JLabel();
        lastname_label = new javax.swing.JLabel();
        last_name_field = new javax.swing.JTextField();
        first_name_field = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        conform_password_label = new javax.swing.JLabel();
        phone_number_label = new javax.swing.JLabel();
        phone_number_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        conform_password_field = new javax.swing.JPasswordField();
        gender_label = new javax.swing.JLabel();
        male_radio_button = new javax.swing.JRadioButton();
        female_radio_button = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        account_exists = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        address_field = new javax.swing.JTextField();
        mini_label1 = new javax.swing.JLabel();
        cancel_lable2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        signup_field.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signup_field.setText("SignUp");
        signup_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signup_fieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signup_fieldMouseExited(evt);
            }
        });
        signup_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_fieldActionPerformed(evt);
            }
        });

        jLabel4.setText("By Signing up you agree to the Terms of Use and Privacy policy.");

        firstname_label.setText("First Name");

        lastname_label.setText("Last Name");

        last_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_name_fieldActionPerformed(evt);
            }
        });

        first_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_name_fieldActionPerformed(evt);
            }
        });

        email_label.setText("E-mail");

        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });

        password_label.setText("Password");

        conform_password_label.setText("Conform Password");

        phone_number_label.setText("Phone Number");

        phone_number_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_number_fieldActionPerformed(evt);
            }
        });
        phone_number_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone_number_fieldKeyTyped(evt);
            }
        });

        gender_label.setText("Gender:");

        male_radio_button.setText("Male");

        female_radio_button.setText("Female");
        female_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_radio_buttonActionPerformed(evt);
            }
        });

        account_exists.setBackground(new java.awt.Color(204, 0, 0));
        account_exists.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        account_exists.setForeground(new java.awt.Color(0, 153, 0));
        account_exists.setText("Already Have an account? Login!");
        account_exists.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        account_exists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                account_existsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                account_existsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                account_existsMouseExited(evt);
            }
        });

        address.setText("Address");

        address_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstname_label)
                    .addComponent(lastname_label)
                    .addComponent(email_label)
                    .addComponent(password_label)
                    .addComponent(conform_password_label)
                    .addComponent(signup_field, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(account_exists)
                    .addComponent(phone_number_label)
                    .addComponent(address)
                    .addComponent(address_field, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(conform_password_field)
                    .addComponent(password_field)
                    .addComponent(email_field)
                    .addComponent(first_name_field)
                    .addComponent(last_name_field)
                    .addComponent(phone_number_field)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(gender_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(male_radio_button)
                        .addGap(18, 18, 18)
                        .addComponent(female_radio_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(firstname_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(first_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lastname_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(last_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conform_password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conform_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_number_label)
                .addGap(18, 18, 18)
                .addComponent(phone_number_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_label)
                    .addComponent(male_radio_button)
                    .addComponent(female_radio_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(signup_field)
                .addGap(18, 18, 18)
                .addComponent(account_exists)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        mini_label1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mini_label1.setText(" -");
        mini_label1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mini_label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mini_label1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mini_label1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mini_label1MouseExited(evt);
            }
        });

        cancel_lable2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancel_lable2.setText(" x");
        cancel_lable2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_lable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_lable2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel_lable2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancel_lable2MouseExited(evt);
            }
        });

        jLabel1.setText("SignUp");

        jLabel2.setText("Let us get you an Account!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mini_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel_lable2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cancel_lable2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mini_label1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signup_fieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_fieldMouseEntered

        // Border login_button_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        //login_button.setBorder(login_button_border);
        // login_button.setForeground(Color.black);
        signup_field.setBackground(Color.blue);

    }//GEN-LAST:event_signup_fieldMouseEntered

    private void signup_fieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_fieldMouseExited

        // Border login_button_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        // login_button.setBorder(login_button_border);
        // login_button.setForeground(Color.black);
        signup_field.setBackground(Color.blue);

    }//GEN-LAST:event_signup_fieldMouseExited

    private void signup_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_fieldActionPerformed

    private void mini_label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini_label1MouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_mini_label1MouseClicked

    private void mini_label1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini_label1MouseEntered
        Border mini_label1_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red);
        mini_label1.setBorder(mini_label1_border);
        mini_label1.setForeground(Color.red);
    }//GEN-LAST:event_mini_label1MouseEntered

    private void mini_label1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mini_label1MouseExited
        Border mini_label1_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        mini_label1.setBorder(mini_label1_border);
        mini_label1.setForeground(Color.black);
    }//GEN-LAST:event_mini_label1MouseExited

    private void cancel_lable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_lable2MouseClicked

        System.exit(0);

    }//GEN-LAST:event_cancel_lable2MouseClicked

    private void cancel_lable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_lable2MouseEntered
        Border cancel_label2_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red);
        cancel_lable2.setBorder(cancel_label2_border);
        cancel_lable2.setForeground(Color.red);
    }//GEN-LAST:event_cancel_lable2MouseEntered

    private void cancel_lable2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_lable2MouseExited
        Border cancel_label2_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        cancel_lable2.setBorder(cancel_label2_border);
        cancel_lable2.setForeground(Color.black);
    }//GEN-LAST:event_cancel_lable2MouseExited

    private void last_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_name_fieldActionPerformed

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    private void female_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_radio_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_radio_buttonActionPerformed

    private void phone_number_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_number_fieldKeyTyped
        // creating text field accept only numbers
        String phone_no = " "; // all numbers stored to make a phone number
        char number = evt.getKeyChar();
        // make sure phone number field has no other than numbers
        if(((number < '0')|| (number > '9')))
            evt.consume();  // ignore the char
        // make sure phone number has not more than 10 digits
        phone_no = phone_number_field.getText(); // get the string from the text box
        if(phone_no.length() > 9) // get the length and compare
            evt.consume(); // ignore the char
    }//GEN-LAST:event_phone_number_fieldKeyTyped

    private void phone_number_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_number_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_number_fieldActionPerformed

    private void account_existsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_account_existsMouseClicked
        // creating a connection to login form

        Login_Form lf = new Login_Form();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_account_existsMouseClicked

    private void account_existsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_account_existsMouseEntered

        Border new_account_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color (0,153,0));
        account_exists.setBorder(new_account_border);

    }//GEN-LAST:event_account_existsMouseEntered

    private void account_existsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_account_existsMouseExited

        account_exists.setBorder(null);
    }//GEN-LAST:event_account_existsMouseExited

    private void address_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_fieldActionPerformed

    private void first_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_name_fieldActionPerformed

    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account_exists;
    private javax.swing.JLabel address;
    private javax.swing.JTextField address_field;
    private javax.swing.JLabel cancel_lable2;
    private javax.swing.JPasswordField conform_password_field;
    private javax.swing.JLabel conform_password_label;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_label;
    private javax.swing.JRadioButton female_radio_button;
    private javax.swing.JTextField first_name_field;
    private javax.swing.JLabel firstname_label;
    private javax.swing.JLabel gender_label;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField last_name_field;
    private javax.swing.JLabel lastname_label;
    private javax.swing.JRadioButton male_radio_button;
    private javax.swing.JLabel mini_label1;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField phone_number_field;
    private javax.swing.JLabel phone_number_label;
    private javax.swing.JButton signup_field;
    // End of variables declaration//GEN-END:variables
}
